//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMvcCountriesRouting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public Nullable<long> Population { get; set; }
        public string FlagURL { get; set; }
    }
}
